# -*- coding: utf-8 -*-
"""Advanced_Movie_Recommendation_System_MovieLens100K_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBYjD4uAPPNRkP3me8ndN8rBjIxnXlCC

# 🎬 Advanced Movie Recommendation System (MovieLens 100K)
## Beginner-Friendly ML Capstone

This notebook demonstrates:
- EDA
- Visualizations
- User-Movie Matrix
- Item-Based Collaborative Filtering (Cosine Similarity)
- Movie Recommendations
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity

!wget -q https://files.grouplens.org/datasets/movielens/ml-100k.zip
!unzip -qo ml-100k.zip

ratings=pd.read_csv('ml-100k/u.data',sep='\t',
names=['user_id','movie_id','rating','timestamp'])

movies=pd.read_csv('ml-100k/u.item',
sep='|',
encoding='latin-1',
header=None,
usecols=[0,1],
names=['movie_id','title'])

df=ratings.merge(movies,on='movie_id')
df.head(50)

"""## Exploratory Data Analysis"""

print(df.shape , "\n")
print(df.isnull().sum(), "\n")
print(df['rating'].describe())

plt.figure(figsize=(6,4))
df['rating'].hist(bins=5)
plt.title('Rating Distribution')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

top=df['title'].value_counts().head(10)
plt.figure(figsize=(10,5))
top.sort_values().plot(kind='barh')
plt.title('Top 10 Most Rated Movies')
plt.show()

movie_matrix=df.pivot_table(index='user_id',
columns='title',
values='rating')
movie_matrix.head()

"""## Cosine Similarity"""

movie_similarity=cosine_similarity(movie_matrix.fillna(0).T)
similarity_df=pd.DataFrame(movie_similarity,
index=movie_matrix.columns,
columns=movie_matrix.columns)
similarity_df.iloc[:5,:5]

pearson_correlation = movie_matrix.corr(method='pearson')
pearson_correlation.head()

"""Now, let's create a recommendation function using Pearson Correlation and compare its output with the Cosine Similarity results."""

def recommend_pearson(movie_name, n=10):
    scores = pearson_correlation[movie_name].sort_values(ascending=False)
    return scores.iloc[1:n+1]

# Get recommendations for the same movie ('Star Wars (1977)') using Pearson Correlation
movie_for_comparison = 'Star Wars (1977)'
rec_pearson = recommend_pearson(movie_for_comparison)

plt.figure(figsize=(8,5))
rec_pearson.sort_values().plot(kind='barh')
plt.title(f'Top Recommendations for {movie_for_comparison} (Pearson Correlation)')
plt.xlabel('Pearson Correlation')
plt.show()

plt.figure(figsize=(10,8))
subset=similarity_df.iloc[:20,:20]
plt.imshow(subset,cmap='viridis')
plt.title('Movie Similarity Heatmap (20 Movies)')
plt.colorbar()
plt.xticks(range(20),subset.columns,rotation=90,fontsize=6)
plt.yticks(range(20),subset.index,fontsize=6)
plt.show()

def recommend(movie_name,n=10):
    scores=similarity_df[movie_name].sort_values(ascending=False)
    return scores.iloc[1:n+1]

recommend('Legends of the Fall (1994)')

movie='Star Wars (1977)'
rec=recommend(movie)
plt.figure(figsize=(8,5))
rec.sort_values().plot(kind='barh')
plt.title(f'Top Recommendations for {movie}')
plt.xlabel('Cosine Similarity')
plt.show()

"""## Exercises
1. Recommend for another movie.
2. Compare Cosine Similarity vs Pearson Correlation.
3. Add TMDb posters.
4. Build a Streamlit interface.
5. Evaluate recommendations.
"""